# Generated by Django 3.0 on 2021-06-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('uemail', models.EmailField(max_length=20)),
                ('Rollno', models.CharField(max_length=10)),
                ('sage', models.IntegerField()),
                ('dob', models.DateField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('age', models.IntegerField()),
                ('rollno', models.CharField(max_length=10)),
                ('addres', models.TextField(null=True)),
                ('sgpa', models.DecimalField(decimal_places=4, max_digits=6)),
                ('cgpa', models.FloatField(null=True)),
                ('dob', models.DateField()),
                ('timet', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='images/')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('done', models.BooleanField(default=False, verbose_name='languages')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SingUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('age', models.IntegerField(verbose_name='age')),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
