# Generated by Django 3.0 on 2021-06-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dar', '0002_register_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='myreg',
            name='addres',
            field=models.TextField(default=False),
        ),
    ]
