# Generated by Django 3.0 on 2021-06-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dar', '0003_myreg_addres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreg',
            name='addres',
            field=models.CharField(max_length=30),
        ),
    ]
